spring:
  application:
    name: distributed-rate-limiter

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
    timeout: 2000ms

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

ratelimiter:
  default:
    algorithm: TOKEN_BUCKET
    limit: 1000
    windowSeconds: 60

  algorithms:
    token-bucket:
      enabled: true
    sliding-window-log:
      enabled: true
    sliding-window-counter:
      enabled: true
    fixed-window:
      enabled: true

logging:
  level:
    com.saurabh.ratelimiter: INFO
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"