
version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rate-limiter-network

  rate-limiter:
    build: .
    container_name: rate-limiter-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: rate-limiter-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - rate-limiter-network

  grafana:
    image: grafana/grafana:latest
    container_name: rate-limiter-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    networks:
      - rate-limiter-network

volumes:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  rate-limiter-network:
    driver: bridge